volumes:
  node_modules:
  minio_storage:

services:
  spider:
    build:
      context: .
      target: dev
    container_name: intranet-archive
    env_file:
      - .env
    environment:
      ORDINAL_NUMBER: 0
      VIRTUAL_HOST: app.archive.intranet.docker
      VIRTUAL_PORT: "2000"
      S3_ENDPOINT: "http://intranet-archive-minio:9010"
    volumes:
      - node_modules:/home/node/app/node_modules
      - ./conf/node:/home/node/app
    ports:
      - "2000:2000"
    depends_on:
      minio-init:
        # Wait for minio-init to complete before starting.
        condition: service_completed_successfully
    # Requests to intranet.docker and cdn.intranet.docker should go to host machine
    extra_hosts:
      - "intranet.docker:host-gateway"
      - "cdn.intranet.docker:host-gateway"

  minio:
    image: minio/minio
    container_name: intranet-archive-minio
    ports:
      - "9010:9010"
      - "9011:9011"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      MINIO_ADDRESS: ':9010'
      MINIO_CONSOLE_ADDRESS: ':9011'
      VIRTUAL_HOST: minio.archive.intranet.docker
      VIRTUAL_PORT: "9011"
    command: server --console-address ":9011" /data
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9010' || exit 1
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 2

  minio-init:
    image: minio/mc
    container_name: intranet-archive-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: |
      /bin/sh -c "
        mc config host add intranet-archive http://intranet-archive-minio:9010 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}
        mc mb --ignore-existing intranet-archive/${S3_BUCKET_NAME} --region eu-west-2
        mc anonymous set download intranet-archive/${S3_BUCKET_NAME};
        exit 0
      "

  cdn:
    image: caddy:2-alpine
    container_name: intranet-archive-cdn
    volumes:
      - ./conf/local.Caddyfile:/etc/caddy/Caddyfile
    environment:
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      VIRTUAL_HOST: archive.intranet.docker
      VIRTUAL_PORT: 2029
    depends_on:
      - minio
    ports:
      - "2029:2029"
