volumes:
  node_modules:

services:
  spider:
    build:
      context: .
      target: dev
    env_file:
      - .env
    container_name: intranet-archive
    environment:
      VIRTUAL_HOST: app.archive.intranet.docker
      VIRTUAL_PORT: "8080"
    volumes:
      - node_modules:/usr/local/bin/node/node_modules
      - ./snapshots:/archiver/snapshots
      - ./conf/node:/usr/local/bin/node
    ports:
      - "8090:8080"
