version: "3"
services:
  spider:
    build: .
    env_file:
      - .env
    container_name: intranet-archive
    environment:
      VIRTUAL_HOST: spider.intranet.docker
      VIRTUAL_PORT: "8080"
    volumes:
      - ./snapshots:/archiver/snapshots
    ports:
      - "8080:8080"
