version: "3"
services:
  spider:
    build: .
    container_name: intranet-archive
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      VIRTUAL_HOST: spider.intranet.docker
      VIRTUAL_PORT: "8080"
    volumes:
      - ./spider:/root/websites
    ports:
      - "8080:8080"
    restart: unless-stopped

