services:
  spider-prod:
    build:
      context: .
      target: build-prod
    env_file:
      - .env
    container_name: intranet-archive-prod
    environment:
      VIRTUAL_HOST: app.archive.intranet.docker
      VIRTUAL_PORT: "2000"
    ports:
      - "2000:2000"
