version: "3"
services:
  spider:
    build: .
    env_file:
      - .env
    container_name: intranet-archive
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      VIRTUAL_HOST: spider.intranet.docker
      VIRTUAL_PORT: "8080"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - ./spider:/root/websites
      - ~/.aws:/root/.aws
    ports:
      - "8080:8080"
    restart: unless-stopped

