services:
  spider-prod:
    build:
      context: .
      target: build-prod
    env_file:
      - .env
    container_name: intranet-archive-prod
    environment:
      VIRTUAL_HOST: spider.intranet.docker
      VIRTUAL_PORT: "8080"
    volumes:
      - ./snapshots:/archiver/snapshots
    ports:
      - "8080:8080"
