{
 "title": "CDPT / Intranet Archive",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(intranet_access,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bucket Access",
   "type": "stat",
   "description": "Can the service access the S3 bucket",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bucket_access{namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Snapshot Count",
   "type": "timeseries",
   "description": "The number of snapshots taken",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by(agency, env) (snapshot_count{namespace=\"intranet-archive-dev\"})",
     "legendFormat": "{{env}}:{{agency}}"
    }
   ]
  },
  {
   "title": "Most Recent Snapshot Age",
   "type": "timeseries",
   "description": "The age of the most recent snapshot",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "min by(agency, env) (most_recent_snapshot_age{namespace=\"intranet-archive-dev\"})",
     "legendFormat": "{{env}}:{{agency}}"
    }
   ]
  },
  {
   "title": "CDN Access Forbidden",
   "type": "stat",
   "description": "Is unauthorised access to the CDN forbidden",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cdn_forbidden{namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Intranet Access",
   "type": "barchart",
   "description": "Can the service access the intranet",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "min by(env) (intranet_access{namespace=\"intranet-archive-dev\"})",
     "legendFormat": "{{env}}"
    }
   ]
  }
 ]
}