apiVersion: v1
kind: Secret
metadata:
  name: intranet-archive-dev-secrets
type: Opaque
stringData:
  INTRANET_JWT_DEV: "${INTRANET_JWT_DEV}"
  INTRANET_JWT_STAGING: "${INTRANET_JWT_STAGING}"
  INTRANET_JWT_PRODUCTION: "${INTRANET_JWT_PRODUCTION}"
  INTRANET_ARCHIVE_SHARED_SECRET: "${INTRANET_ARCHIVE_SHARED_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: intranet-archive-dev-base64-secrets
type: Opaque
data:
  AWS_CLOUDFRONT_PRIVATE_KEY: "${AWS_CLOUDFRONT_PRIVATE_KEY_BASE64}"
  AWS_CLOUDFRONT_PUBLIC_KEY: "${AWS_CLOUDFRONT_PUBLIC_KEY_BASE64}"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudfront-input
type: Opaque
data:
  AWS_CLOUDFRONT_PUBLIC_KEY: "${AWS_CLOUDFRONT_PUBLIC_KEY_BASE64}"
  # AWS_CLOUDFRONT_PUBLIC_KEY_EXPIRING: "${AWS_CLOUDFRONT_PUBLIC_KEY_EXPIRING_BASE64}"
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
type: Opaque
data:
  auth: "${BASIC_AUTH_BASE64}"
