apiVersion: v1
kind: Secret
metadata:
  name: intranet-archive-dev-secrets
type: Opaque
stringData:
  ACCESS_TOKEN: "${ACCESS_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudfront-input
type: Opaque
data:
  AWS_CLOUDFRONT_PUBLIC_KEY: "${AWS_CLOUDFRONT_PUBLIC_KEY_BASE64}"
  # AWS_CLOUDFRONT_PUBLIC_KEY_EXPIRING: "${AWS_CLOUDFRONT_PUBLIC_KEY_EXPIRING_BASE64}"
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
type: Opaque
data:
  auth: "${BASIC_AUTH_BASE64}"
