name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'CDPT-768-temp-creds-aws'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Assume role in Cloud Platform
      - name: Assume role in Cloud Platform
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}
      
      # Login to container repository
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build
        run: docker build -t ${{ vars.ECR_URL }}:${{ github.sha }} -t ${{ vars.ECR_URL }}:dev.latest .

      - name: Push to ECR
        id: ecr
        run:  docker push ${{ vars.ECR_URL }} --all-tags

  